@startuml class regions

  interface models.IndexModel {
      +sequelize : Sequelize
      +models : RegionModel
      +Op : sequelize
  }

  class models.RegionModel{
     +region_id : integer
     +region_name : string
  }

  models.IndexModel --> models.RegionModel

  interface routes.IndexRoute{
    +regions : RegionRoute
  }

  class routes.RegionRoute{
    +post : Router()
    +get  :Router()
    +put : Router()
    +delete : Router()
  }

  

  class Index {
    +app : express()
  }

  interface controllers.IndexController{
    +regions : RegionsController
  }

  class controllers.RegionsController{
    +findRegionSQLRaw()
    +findRegionMethod()
  }

  routes.IndexRoute --> routes.RegionRoute
  routes.RegionRoute -left-> models.IndexModel
  routes.RegionRoute -right-> controllers.IndexController
  controllers.RegionsController -left-> models.IndexModel
  controllers.IndexController --> controllers.RegionsController

  Index --> models.IndexModel
  Index --> routes.IndexRoute



@enduml