@startuml class regions

  interface models.IndexModel {
      +sequelize
      +models
      +Op : sequelize
  }

  class models.RegionModel{
     +region_id : integer
     +region_name : string
  }

  models.IndexModel --> models.RegionModel

  interface routes.IndexRoute{
    +regions : regionroute
  }

  class routes.RegionRoute{
    +post : http
    +get  :http
    +put : http
    +delete : http
  }

  

  class Index {

  }

  interface controllers.IndexController{

  }

  class controllers.RegionsController{
    +findRegionSQLRaw
    +findRegionMethod
  }

  routes.IndexRoute --> routes.RegionRoute
  routes.RegionRoute -left-> models.IndexModel
  routes.RegionRoute -right-> controllers.IndexController
  controllers.RegionsController -left-> models.IndexModel
  controllers.IndexController --> controllers.RegionsController

  Index --> models.IndexModel
  Index --> routes.IndexRoute



@enduml